msgbox "This is a time management program made by Vivain Innovaters"
msgbox "This project aims to provide easy time management to the youth of India"
msgbox "More specifically by blocking social media apps and setting app timers"
msgbox "Please download from https://samayrakshat.carrd.co/"
msgbox "Made only with python"
msgbox "Thank you"
